## This is for testing not part of notebook

In [ ]:
import numpy as np
archive = np.load('images/patient_002.npz')
scan = archive['scan']
mask = archive['mask']
# scan.shape equals mask.shape

In [ ]:
from numpy import load

data = load('images/patient_002.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

scan
[[[-777 -819 -812 ...   49   50   51]
  [-759 -826 -820 ...   72   61   51]
  [-707 -785 -796 ...   67   48   29]
  ...
  [-774 -757 -714 ...   48   48   49]
  [-679 -610 -518 ...   15   30   44]
  [-472 -365 -279 ...   32   33   34]]

 [[-783 -817 -817 ...   24   32   41]
  [-791 -854 -842 ...   66   56   45]
  [-774 -854 -844 ...   86   60   34]
  ...
  [-808 -812 -809 ...   46   51   56]
  [-779 -752 -692 ...   16   32   48]
  [-653 -578 -472 ...   38   30   22]]

 [[-804 -804 -812 ...   13   25   37]
  [-841 -855 -843 ...   57   46   35]
  [-827 -860 -847 ...  117   86   55]
  ...
  [-807 -818 -827 ...   51   56   61]
  [-808 -804 -778 ...   33   41   48]
  [-767 -729 -636 ...   42   33   24]]

 ...

 [[  48   43   40 ... -723 -560 -398]
  [  42   44   44 ... -700 -562 -424]
  [  27   30   28 ... -596 -469 -341]
  ...
  [   5   -7  -20 ...  -80  -54  -28]
  [ -21  -33  -48 ...  -65  -38  -11]
  [   9    7   -3 ...  -47  -39  -32]]

 [[  45   42   37 ... -921 -844 -767]
  [  30

https://challengedata.ens.fr/participants/challenges/33/

In [3]:
python


NameError: name 'npzviewer' is not defined

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=ff46915c-5d98-4aea-b947-cb4657d60849' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>